-- http://en.wikipedia.org/wiki/Districts_of_Malaysia

INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (1, 10, '0110', 'GOMBAK');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (2, 10, '0210', 'HULU LANGAT');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (3, 10, '0310', 'HULU SELANGOR');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (4, 10, '0410', 'KLANG');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (5, 10, '0510', 'KUALA LANGAT');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (6, 10, '0610', 'KUALA SELANGOR');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (7, 10, '0710', 'PETALING');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (8, 10, '0810', 'SABAK BERNAM');

INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (9, 1, '0101', 'BATU PAHAT');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (10, 1, '0201', 'JOHOR BAHRU');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (11, 1, '0301', 'KLUANG');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (12, 1, '0401', 'KOTA TINGGI');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (13, 1, '0501', 'MERSING');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (14, 1, '0601', 'MUAR');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (15, 1, '0701', 'MUAR');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (16, 1, '0801', 'PONTIAN');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (17, 1, '0901', 'SEGAMAT');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (18, 1, '1001', 'KULAIJAYA');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (19, 2, '1101', 'LEDANG');


INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (20, 2, '0102', 'BALING');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (21, 2, '0202', 'BANDAR BAHARU');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (22, 2, '0302', 'KOTA SETAR');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (23, 2, '0402', 'KUALA MUDA');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (24, 2, '0502', 'KUBANG PASU');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (25, 2, '0602', 'KULIM');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (26, 2, '0702', 'PULAU LANGKAWI');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (27, 2, '0802', 'PADANG TERAP');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (28, 2, '0902', 'PENDANG');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (29, 2, '1002', 'POKOK SENA');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (30, 2, '1102', 'SIK');
INSERT INTO DISTRICT (ID, STATE_ID, CODE, DESCRIPTION) VALUES (31, 2, '1202', 'YAN');

PERAK
Batang Padang
Hilir Perak
Hulu Perak
Kerian
Kinta
Kuala Kangsar
Larut, Matang
Selama
Manjung
Perak Tengah

KELANTAN
Bachok
Gua Musang
Jeli
Kota Baharu
Kuala Krai
Machang
Pasir Mas
Pasir Puteh
Tanah Merah
Tumpat